<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ConferenceAssistant.Core\ConferenceAssistant.Core.csproj" />
    <ProjectReference Include="..\ConferenceAssistant.Ingestion\ConferenceAssistant.Ingestion.csproj" />
    <ProjectReference Include="..\ConferenceAssistant.Agents\ConferenceAssistant.Agents.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
